#!/bin/sh

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

# run npm prepush command
npm run prepush

if [ $? -eq 0 ]
then
    echo "${green}------------------------------"
    echo "pre-push success"
    echo "------------------------------${reset}"
else
    echo "${red}------------------------------"
    echo "pre-push failure"
    echo "------------------------------${reset}"
fi
